### ISSUE TITLE
Example code showing how to use the scripts would be helpful

### ISSUE THREAD

**Issue by windnage** [mgraber/tiger_maf_xwalk#6]
@mgraber I'm having trouble understanding how I would run your scripts for areas other than the sample Denver data. Some example code and an explanation of how to do that would be invaluable. 
Thanks,
Ann

**Comment by mgraber** [comment]
Thanks @windnage. I addressed this issue by providing the code for converting shapefiles, as downloaded in the link provided in the README, to CSVs. I also included a description of where a user should change the county code in order to run the workflow for another county. This should allow a user to download another county's TIGER data, convert it, then change two parameters in order to run the workflow.

I also moved the summary steps earlier in the README to help make this more understandable.
